=== lishengze/Docs-Notes/future_doc/NetMonitor_vss/datamodel/commonEnv/DB.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v2004 rel. 4 U (http://www.xmlspy.com)-->
<!ELEMENT DB (schemas, tableGroups, entities, checkrights?)>
<!ATTLIST DB
	author CDATA #REQUIRED
	version CDATA #REQUIRED
	notnull (no) #REQUIRED
	iskey (no) #REQUIRED
	order (asc) #REQUIRED
	unique (no) #REQUIRED
>
<!ELEMENT schemas (schema*)>
<!ATTLIST schema
	name CDATA #REQUIRED
>
<!ELEMENT schema (tableGroup*)>
<!ATTLIST tableGroup
	name CDATA #REQUIRED
>
<!ELEMENT tableGroup (setColumn | setIndex)*>
<!ATTLIST setColumn
	columnName CDATA #REQUIRED
	tableName CDATA #IMPLIED
	setIskey (no | yes) #IMPLIED
	setNotnull (no | yes) #IMPLIED
>
<!ELEMENT setColumn EMPTY>
<!ATTLIST setIndex
	indexName CDATA #REQUIRED
	tableName CDATA #IMPLIED
	setUnique (no | yes) #IMPLIED
	setDelete (yes) #IMPLIED
>
<!ELEMENT setIndex EMPTY>

<!ELEMENT tableGroups (tables*)>
<!ELEMENT tables (table*)>
<!ATTLIST tables
	group CDATA #REQUIRED
>
<!ELEMENT table (Columns, Index)>
<!ATTLIST table
	name CDATA #REQUIRED
	title CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT Columns (Column*)>
<!ATTLIST Columns
	ref CDATA #IMPLIED
>
<!ELEMENT Column EMPTY>
<!ATTLIST Column
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	label CDATA #REQUIRED
	description CDATA #IMPLIED
	default CDATA #IMPLIED
	notnull (no | yes) #IMPLIED
	iskey (no | yes) #IMPLIED
	originaltype CDATA #REQUIRED
	basetype CDATA #REQUIRED
	length CDATA #REQUIRED
	precision CDATA #REQUIRED
>
<!ELEMENT Index (defineIndex*)>
<!ELEMENT defineIndex (key*)>
<!ATTLIST defineIndex
	name CDATA #REQUIRED
	unique (yes | no) #IMPLIED
	label CDATA #REQUIRED
>
<!ELEMENT key EMPTY>
<!ATTLIST key
	name CDATA #REQUIRED
	order (asc | desc) #IMPLIED
>
<!ELEMENT entities (Entity*)>
<!ELEMENT Entity ((Field | Ref)*)>
<!ATTLIST Entity
	name CDATA #REQUIRED
	title CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT Field EMPTY>
<!ATTLIST Field
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	label CDATA #REQUIRED
	description CDATA #IMPLIED
	notnull (no | yes) #IMPLIED
	iskey (no | yes) #IMPLIED
>
<!ELEMENT Ref EMPTY>
<!ATTLIST Ref
	entity CDATA #REQUIRED
	iskey (yes | no) #IMPLIED
>
<!ELEMENT checkrights (checkfields, checktables)>
<!ELEMENT checkfields (checkfield*)>
<!ELEMENT checkfield EMPTY>
<!ATTLIST checkfield
	name CDATA #REQUIRED
	default (yes | no) #REQUIRED
>
<!ELEMENT checktables (checktable*)>
<!ELEMENT checktable (checkitem*)>
<!ATTLIST checktable
	group CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT checkitem EMPTY>
<!ATTLIST checkitem
	name CDATA #REQUIRED
	fieldname CDATA #IMPLIED
	default (yes | no) #IMPLIED
	convertfunction CDATA #IMPLIED
>

=== lishengze/Docs-Notes/future_doc/NetMonitor_vss/datamodel/env/DBMisc.xml
<?xml version="1.0" encoding="gb2312"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by think (think) -->
<!DOCTYPE DB SYSTEM "../commonEnv/DB.dtd">
<DB author="zhoujj" version="1" iskey="no" notnull="no" order="asc" unique="no">
	<schemas>
		<schema name="attr">
			<tableGroup name="monitor"/>
		</schema>
	</schemas>
	<tableGroups>
		<tables group="monitor">
			<table name="DbWriteLog" title="据库写记录日志" description="">
				<Columns ref="DbWriteLog"/>
				<Index/>
			</table>
			<table name="SysHistoryObjectAttr" title="历史状态信息表" description="">
				<Columns ref="SysHistoryObjectAttr"/>
				<Index/>
			</table>
			<table name="SysFrontInfo" title="前置响应信息表" description="">
				<Columns ref="SysFrontInfo"/>
				<Index/>
			</table>
			<table name="SysWarningEvent" title="告警事件信息表" description="">
				<Columns ref="SysWarningEvent"/>
				<Index/>
			</table>
			<table name="SysRegisterUserInfo" title="用户信息表" description="">
				<Columns ref="SysRegisterUserInfo"/>
				<Index/>
			</table>
			<table name="RspQryTopCpuInfo" title="Cpu信息表" description="">
				<Columns ref="TopCpuInfo2"/>
				<Index/>
			</table>
			<table name="RspQryTopMemInfo" title="Mem信息表" description="">
				<Columns ref="RspQryTopMemInfo"/>
				<Index/>
			</table>
			<table name="RspQryNetworkInfo" title="Network信息表" description="">
				<Columns ref="RspQryNetworkInfo"/>
				<Index/>
			</table>
			<table name="SysHistoryTradePeak" title="历史峰值信息表" description="">
				<Columns ref="SysHistoryTradePeak"/>
				<Index/>
			</table>
			<table name="SysNetDevice" title="网络设备" description="">
				<Columns ref="SysNetDevice"/>
				<Index/>
			</table>
			<table name="SysNetDeviceLinked" title="网络设备连接关系" description="">
				<Columns ref="SysNetDeviceLinked"/>
				<Index/>
			</table>
			<table name="SysNetArea" title="网络大区划分" description="">
				<Columns ref="SysNetArea"/>
				<Index/>
			</table>
			<table name="SysNetSubArea" title="网络子区" description="">
				<Columns ref="SysNetSubArea"/>
				<Index/>
			</table>
			<table name="SysNetSubAreaIP" title="网络子区IP" description="">
				<Columns ref="SysNetSubAreaIP"/>
				<Index/>
			</table>
			<table name="SysNetBuilding" title="大楼" description="">
				<Columns ref="SysNetBuilding"/>
				<Index/>
			</table>
			<table name="SysNetRoom" title="机房" description="">
				<Columns ref="SysNetRoom"/>
				<Index/>
			</table>
			<table name="SysNetCabinets" title="机柜" description="">
				<Columns ref="SysNetCabinets"/>
				<Index/>
			</table>
			<table name="SysNetDeviceType" title="网络设备类型" description="">
				<Columns ref="SysNetDeviceType"/>
				<Index/>
			</table>
			<table name="SysNetOID" title="OID" description="">
				<Columns ref="SysNetOID"/>
				<Index/>
			</table>
			<table name="SysNetTimePolicy" title="时间策略" description="">
				<Columns ref="SysNetTimePolicy"/>
				<Index/>
			</table>
			
			<table name="SysNetGatherTask" title="采集任务" description="">
				<Columns ref="SysNetGatherTask"/>
				<Index/>
			</table>
			<table name="SysNetDeviceCategory" title="常用设备类别" description="">
				<Columns ref="SysNetDeviceCategory"/>
				<Index/>
			</table>
			<table name="SysNetManufactory" title="设备厂商" description="">
				<Columns ref="SysNetManufactory"/>
				<Index/>
			</table>
			<table name="SysNetCommunity" title="设备共同体" description="">
				<Columns ref="SysNetCommunity"/>
				<Index/>
			</table>
			<table name="SysNetPortType" title="端口类型" description="">
				<Columns ref="SysNetPortType"/>
				<Index/>
			</table>
			<table name="SysNetInterface" title="端口" description="">
				<Columns ref="SysNetInterface"/>
				<Index/>
			</table>
			<table name="SysNetGeneralOID" title="通用OID" description="">
				<Columns ref="SysNetGeneralOID"/>
				<Index/>
			</table>
			<table name="SysNetMonitorType" title="监控对象类别" description="">
				<Columns ref="SysNetMonitorType"/>
				<Index/>
			</table>
			<table name="SysNetMonitorAttrScope" title="指标统表" description="">
				<Columns ref="SysNetMonitorAttrScope"/>
				<Index/>
			</table>
			<table name="SysNetMonitorAttrType" title="监控指标表" description="">
				<Columns ref="SysNetMonitorAttrType"/>
				<Index/>
			</table>
			<table name="SysNetFuncArea" title="职能区" description="">
				<Columns ref="SysNetFuncArea"/>
				<Index/>
			</table>
			<table name="SysNetMonitorCommandType" title="监控指令表" description="">
				<Columns ref="SysNetMonitorCommandType"/>
				<Index/>
			</table>
			<table name="SysNetMonitorActionGroup" title="动作族表" description="">
				<Columns ref="SysNetMonitorActionGroup"/>
				<Index/>
			</table>
			<table name="SysNetMonitorDeviceGroup" title="设备对象组表" description="">
				<Columns ref="SysNetMonitorDeviceGroup"/>
				<Index/>
			</table>
			<table name="SysNetMonitorTaskInfo" title="任务信息表" description="">
				<Columns ref="SysNetMonitorTaskInfo"/>
				<Index/>
			</table>
			<table name="SysNetPartyLinkInfo" title="会员链路信息表" description="">
				<Columns ref="SysNetPartyLinkInfo"/>
				<Index/>
			</table>
			<table name="SysNetDelPartyLinkInfo" title="会员链路信息表" description="">
				<Columns ref="SysNetDelPartyLinkInfo"/>
				<Index/>
			</table>
			<table name="SysNetPartyLinkAddrChange" title="会员链路信息表" description="">
				<Columns ref="SysNetPartyLinkAddrChange"/>
				<Index/>
			</table>
			<table name="SysNetMonitorActionAttr" title="监控动作指标对照表" description="">
				<Columns ref="SysNetMonitorActionAttr"/>
				<Index/>
			</table>
			<table name="SysNetModule" title="模块" description="">
				<Columns ref="SysNetModule"/>
				<Index/>
			</table>
			<table name="SysNetEventExpr" title="告警表达式信息表" description="">
				<Columns ref="SysNetEventExpr"/>
				<Index/>
			</table>
			<table name="SysNetEventType" title="事件类型" description="">
				<Columns ref="SysNetEventType"/>
				<Index/>
			</table>
			<table name="SysNetSubEventType" title="事件子类型" description="">
				<Columns ref="SysNetSubEventType"/>
				<Index/>
			</table>
			<table name="SysNetEventLevel" title="事件级别" description="">
				<Columns ref="SysNetEventLevel"/>
				<Index/>
			</table>
			<table name="SysNetMonitorDeviceTask" title="任务结果规则分析表" description="">
				<Columns ref="SysNetMonitorDeviceTask2"/>
				<Index/>
			</table>
			<table name="SysNetMonitorTaskInstAttrs" title="任务指令指标集表" description="">
				<Columns ref="SysNetMonitorTaskInstAttrs"/>
				<Index/>
			</table>		
			<table name="SysNetMonitorTaskResult" title="任务结果表" description="">
				<Columns ref="SysNetMonitorTaskResult"/>
				<Index/>
			</table>			
			<table name="SysNetBaseLine" title="基线表" description="">
				<Columns ref="SysNetBaseLine"/>
				<Index/>
			</table>
			<table name="SysNetBaseLineTask" title="基线任务表" description="">
				<Columns ref="SysNetBaseLineTask"/>
				<Index/>
			</table>
			<table name="SysNetBaseLineResult" title="基线结果表" description="">
				<Columns ref="SysNetBaseLineResult"/>
				<Index/>
			</table>						
			<table name="SysNetPartyLinkStatusInfo" title="会员链路状态信息表" description="">
				<Columns ref="SysNetPartyLinkStatusInfo"/>
				<Index/>
			</table>	

			<table name="SysNetMemberSDHLineInfo" title="会员SDH线路明细表" description="">
				<Columns ref="SysNetMemberSDHLineInfo"/>
				<Index/>
			</table>	
			<table name="SysNetDDNLinkInfo" title="DDN链路信息表" description="">
				<Columns ref="SysNetDDNLinkInfo"/>
				<Index/>
			</table>	
			<table name="SysNetPseudMemberLinkInfo" title="非会员线路使用信息" description="">
				<Columns ref="SysNetPseudMemberLinkInfo"/>
				<Index/>
			</table>	

			<table name="SysNetOuterDeviceInfo" title="远端设备信息" description="">
				<Columns ref="SysNetOuterDeviceInfo"/>
				<Index/>
			</table>	
			<table name="SysLocalPingResultInfo" title="本地ping结果" description="">
				<Columns ref="SysLocalPingResultInfo"/>
				<Index/>
			</table>	
			<table name="SysRomotePingResultInfo" title="远程ping结果" description="">
				<Columns ref="SysRomotePingResultInfo"/>
				<Index/>
			</table>	
	
			<table name="SysTradeFrontOrderRttStat" title="交易系统前置报单响应信息" description="">
				<Columns ref="SysTradeFrontOrderRttStat"/>
				<Index/>
			</table>	

			<table name="SysTradeOrderRttCutLine" title="交易系统前置报单分布区间" description="">
				<Columns ref="SysTradeOrderRttCutLine"/>
				<Index/>
			</table>	

			<table name="SysParticTradeOrderStates" title="会员席位交易状态" description="">
				<Columns ref="SysParticTradeOrderStates"/>
				<Index/>
			</table>	

			<table name="RouterInfo" title="系统路由信息" description="">
				<Columns ref="RouterInfo"/>
				<Index/>
			</table>	
			<table name="DiskIO" title="磁盘I/O信息" description="">
				<Columns ref="DiskIO"/>
				<Index/>
			</table>	
			<table name="StatInfo" title="系统状态信息" description="">
				<Columns ref="StatInfo"/>
				<Index/>
			</table>	
			<table name="TopProcessInfo" title="进程信息" description="">
				<Columns ref="MonitorTopProcessInfo"/>
				<Index/>
			</table>	
			<table name="SysEventDescrip" title="事件描述信息" description="">
				<Columns ref="SysEventDescrip"/>
				<Index/>
			</table>
			<table name="SysMemberLinkCost" title="会员链路费用表" description="会员链路费用表">
				<Columns ref="SysMemberLinkCost"/>
				<Index/>
			</table>
			<table name="SysNetPartylinkMonthlyRent" title="会员链路月租表" description="会员链路月租表">
				<Columns ref="SysNetPartylinkMonthlyRent"/>
				<Index/>
			</table>
			<table name="SysNetNonPartyLinkInfo" title="非会员链路信息表" description="非会员链路信息表">
				<Columns ref="SysNetNonPartyLinkInfo"/>
				<Index/>
			</table>
		</tables>
	</tableGroups>
	<entities>
		<Entity name="DbWriteLog" title="数据库写记录日志" description="风险数据库写记录日志" >
			<Field name="TradingDay" label="日期" type="TradingDay" description="日期" notnull="yes" iskey="yes" />
			<Field name="Count" label="已写记录" type="Volume" description="已写记录" />
		</Entity>
	<Entity name="TopCpuInfo2" title="CPU资源使用信息" description="top命令查看的主机CPU资源使用信息">
		<Field name="HostName" type="TypeObjectID" label="主机名称" description="主机名称"  notnull="yes" iskey="yes"/>
		<Field name="MonDate" type="Date" label="采集的日期" description="" notnull="yes" iskey="yes"/>
