=== lishengze/Docs-Notes/future_doc/NetMonitor_vss/datamodel/commonEnv/OFP.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT OFP (packages)>
<!ATTLIST OFP
	author CDATA #REQUIRED
	version CDATA #REQUIRED
	head (OFP) #REQUIRED
	comment CDATA #REQUIRED
	isUp (no) #REQUIRED
	isDown (no) #REQUIRED
	isPrivate (no) #REQUIRED
	isPublic (no) #REQUIRED
	multifield (no) #REQUIRED
	v1use (yes) #REQUIRED
	v2use (yes) #REQUIRED
	NGESuse (yes) #REQUIRED
	XTPPackage (notDefined) #REQUIRED
	OFPRequest (notDefined) #REQUIRED
>
<!ELEMENT packages (package*)>
<!ELEMENT package (field*)>
<!ATTLIST package
	name CDATA #REQUIRED
	comm CDATA #REQUIRED
	vary CDATA #REQUIRED
	isUp (yes) #IMPLIED
	isDown (yes) #IMPLIED
	isPrivate (yes) #IMPLIED
	isPublic (yes) #IMPLIED
	comment CDATA #REQUIRED
	multifield (yes) #IMPLIED
	v1use (no) #IMPLIED
	v2use (no) #IMPLIED
	NGESuse (no) #IMPLIED
	XTPPackage CDATA #IMPLIED
	OFPRequest CDATA #IMPLIED
>
<!ELEMENT field EMPTY>
<!ATTLIST field
	name CDATA #REQUIRED
	type (String|Number|Char|Float|Word) #REQUIRED
	length CDATA #IMPLIED
	comment CDATA #REQUIRED
>

=== lishengze/Docs-Notes/future_doc/NetMonitor_vss/datamodel/env/OFP2Misc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by wangzhaodong (ORiON) -->
<!DOCTYPE OFP SYSTEM "..\commonEnv\OFP.dtd">
<OFP author="王肇东" head="OFP" version="1" comment="上海期货交易所原有通讯协议" isUp="no" isDown="no" isPrivate="no" isPublic="no" multifield="no" v1use="yes" v2use="yes">
	<packages>
		<package name="LoginRequest" vary="0x0401" comm="login" comment="用户登录指令" isUp="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
			<field name="Transferid" type="Number" length="8" comment="私有流最大编号"/>
		</package>
		<package name="LoginResponse" vary="0x0501" comm="OK" comment="用户登录应答" isDown="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="Password" type="String" length="40" comment="口令"/>
			<field name="Usernm" type="String" length="8" comment="交易员姓名"/>
			<field name="Localno0" type="String" length="8" comment="交易员用最大本地编号"/>
			<field name="Time" type="String" length="8" comment="交易系统时间"/>
			<field name="Sysstat" type="Number" length="8" comment="交易系统状态"/>
			<field name="Membid" type="String" length="8" comment="所属会员"/>
			<field name="Section" type="String" length="2" comment="当前交易代码"/>
			<field name="Sstatus" type="Char" comment="交易节状态"/>
			<field name="Localno0" type="String" length="8" comment="交易员用最大报单本地编号"/>
			<field name="Transferid" type="Number" length="8" comment="私有流最大编号"/>
		</package>
		<package name="LoginErrorResponse" vary="0x0501" comm="ERROR" comment="用户登录失败应答" isDown="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
			<field name="Transferid" type="Number" length="8" comment="私有流最大编号"/>
		</package>
		<package name="LogoutRequest" vary="0x0407" comm="logout" comment="用户登录退出指令" isUp="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
		</package>
		<package name="LogoutResponse" vary="0x0507" comm="OK" comment="用户登录退出应答" isDown="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
		</package>
		<package name="LogoutErrorResponse" vary="0x0507" comm="ERROR" comment="用户登录退出失败应答" isDown="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
		</package>
		<package name="PasswordUpdateRequest" vary="0x0220" comm="modpwd" comment="用户口令修改指令" isUp="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="OldPasswd" type="String" length="40" comment="旧口令"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
		</package>
		<package name="PasswordUpdateResponse" vary="0x0320" comm="OK" comment="用户口令修改应答" isDown="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="OldPasswd" type="String" length="40" comment="旧口令"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
		</package>
		<package name="PasswordUpdateErrorResponse" vary="0x0320" comm="ERROR" comment="用户口令修改失败应答" isDown="yes">
			<field name="Userid" type="String" length="15" comment="交易员"/>
			<field name="OldPasswd" type="String" length="40" comment="旧口令"/>
			<field name="Passwd" type="String" length="40" comment="口令"/>
		</package>
		<package name="ForceExit" vary="0x0513" comm="killlog" comment="强制退出" isDown="yes"/>
		<package name="SystemWarning" vary="0x2310" comm="" comment="系统警告" isDown="yes">
			<field name="Content" type="String" length="70" comment="警告信息"/>
		</package>
		<package name="SectionStart" vary="0x0522" comm="" comment="系统节开盘" isDown="yes"/>
		<package name="SectionStop" vary="0x0523" comm="" comment="系统节收盘" isDown="yes"/>
		<package name="OpenAuctionStart" vary="0x0524" comm="" comment="系统节开盘集合竞价开始" isDown="yes"/>
		<package name="OpenAuctionSectionStop" vary="0x0525" comm="" comment="系统节开盘集合竞价结束" isDown="yes"/>
		<package name="BuyOrderInsertRequest" vary="0x0202" comm="buy" comment="报单录入指令" isUp="yes">
			<field name="Orderid" type="String" length="8" comment="报单系统编号"/>
			<field name="Commid" type="String" length="6" comment="交易品种"/>
			<field name="Orderp" type="Number" length="6" comment="申报价格"/>
			<field name="Orderv" type="Number" length="6" comment="申报手数"/>
			<field name="Custid" type="String" length="8" comment="客户编码"/>
			<field name="Userid" type="String" length="15" comment="交易员编码"/>
			<field name="Lorderid" type="String" length="8" comment="本地编号"/>
			<field name="Posit" type="Char" comment="买卖方向"/>
			<field name="Closef" type="Char" comment="开平仓标志"/>
			<field name="Tjbz" type="Char" comment="投机保值标志"/>
			<field name="Filler" type="String" length="10" comment="未用"/>
		</package>
		<package name="SellOrderInsertRequest" vary="0x0202" comm="sell" comment="报单录入指令" isUp="yes">
			<field name="Orderid" type="String" length="8" comment="报单系统编号"/>
			<field name="Commid" type="String" length="6" comment="交易品种"/>
			<field name="Orderp" type="Number" length="6" comment="申报价格"/>
			<field name="Orderv" type="Number" length="6" comment="申报手数"/>
			<field name="Custid" type="String" length="8" comment="客户编码"/>
			<field name="Userid" type="String" length="15" comment="交易员编码"/>
			<field name="Lorderid" type="String" length="8" comment="本地编号"/>
			<field name="Posit" type="Char" comment="买卖方向"/>
			<field name="Closef" type="Char" comment="开平仓标志"/>
			<field name="Tjbz" type="Char" comment="投机保值标志"/>
			<field name="Filler" type="String" length="10" comment="未用"/>
		</package>
		<package name="OrderDelRequest" vary="0x0203" comm="delor" comment="报单删除指令" isUp="yes">
			<field name="Orderid" type="String" length="8" comment="报单系统编号"/>
			<field name="Userid" type="String" length="15" comment="交易员编码"/>
		</package>
		<package name="MBackOrder" vary="0x0701" comm="OK" comment="报单修改提醒" isPrivate="yes">
			<field name="mqid" type="Number" length="8" comment="私有流序列号"/>
			<field name="cmd" type="Number" length="4" comment="信息类型"/>
			<field name="Orderid" type="String" length="8" comment="报单系统编号"/>
			<field name="Commid" type="String" length="6" comment="交易品种"/>
			<field name="Orderp" type="Number" length="6" comment="申报价格"/>
			<field name="Orderv" type="Number" length="6" comment="申报手数"/>
			<field name="Custid" type="String" length="8" comment="客户编码"/>
			<field name="Userid" type="String" length="15" comment="交易员编码"/>
			<field name="Lorderid" type="String" length="8" comment="本地编号"/>
			<field name="Posit" type="Char" comment="买卖方向"/>
			<field name="Closef" type="Char" comment="开平仓标志"/>
			<field name="Tjbz" type="Char" comment="投机保值标志"/>
			<field name="Orderf" type="Char" comment="报单状态"/>
			<field name="Orderd" type="String" length="8" comment="报单录入日期"/>
			<field name="Ordert" type="String" length="8" comment="报单录入时间"/>
			<field name="Orderdt" type="String" length="8" comment="报单删除时间"/>
			<field name="Filler" type="String" length="20" comment="未用"/>
		</package>
		<package name="MBackOrderError" vary="0x0701" comm="ERROR" comment="报单修改失败提醒" isPrivate="yes">
			<field name="mqid" type="Number" length="8" comment="私有流序列号"/>
			<field name="cmd" type="Number" length="4" comment="信息类型"/>
			<field name="Orderid" type="String" length="8" comment="报单系统编号"/>
			<field name="Commid" type="String" length="6" comment="交易品种"/>
			<field name="Orderp" type="Number" length="6" comment="申报价格"/>
			<field name="Orderv" type="Number" length="6" comment="申报手数"/>
			<field name="Custid" type="String" length="8" comment="客户编码"/>
			<field name="Userid" type="String" length="15" comment="交易员编码"/>
			<field name="Lorderid" type="String" length="8" comment="本地编号"/>
			<field name="Posit" type="Char" comment="买卖方向"/>
			<field name="Closef" type="Char" comment="开平仓标志"/>
			<field name="Tjbz" type="Char" comment="投机保值标志"/>
			<field name="Filler" type="String" length="10" comment="未用"/>
		</package>
		<package name="MBackTrade" vary="0x0701" comm="OK" comment="成交回报" isPrivate="yes">
			<field name="mqid" type="Number" length="8" comment="私有流序列号"/>
			<field name="cmd" type="Number" length="4" comment="信息类型"/>
			<field name="Orderid" type="String" length="8" comment="报单系统编号"/>
			<field name="Commid" type="String" length="6" comment="交易品种"/>
			<field name="Posit" type="Char" comment="买卖方向"/>
			<field name="Orderv" type="Number" length="6" comment="报单申报手数"/>
			<field name="Orderp" type="Number" length="6" comment="报单申报价格"/>
			<field name="Compv" type="Number" length="6" comment="报单当前成交手数"/>
			<field name="Compp" type="Number" length="6" comment="报单当前成交价格"/>
			<field name="Custid" type="String" length="8" comment="客户编码"/>
			<field name="Userid" type="String" length="15" comment="交易员编码"/>
			<field name="Lorderid" type="String" length="8" comment="本地编号"/>
			<field name="Closef" type="Char" comment="开平仓标志"/>
			<field name="Tjbz" type="Char" comment="投机保值标志"/>
			<field name="Matcno" type="String" length="8" comment="当前撮合编号"/>
			<field name="Compd" type="String" length="8" comment="撮合日期"/>
			<field name="Compt" type="String" length="8" comment="撮合时间"/>
			<field name="Filler" type="String" length="20" comment="未用"/>
		</package>
		<package name="QryDepositRequest" vary="0x0207" comm="eqmag" comment="会员保证金查询指令" isUp="yes">
			<field name="Membid" type="String" length="8" comment="查询起始会员"/>
			<field name="Membidt" type="String" length="8" comment="查询结束会员"/>
		</package>
		<package name="QryDepositResponse" vary="0x0307" comm="OK" comment="会员保证金查询应答" isDown="yes">
			<field name="Membid" type="String" length="8" comment="会员"/>
			<field name="Margit" type="Float" comment="日初资金"/>
			<field name="Credii" type="String" length="15" comment="未使用"/>
			<field name="Buymar" type="Float" comment="买入使用资金"/>
			<field name="Sellma" type="Float" comment="卖出使用资金"/>
			<field name="Totall" type="Float" comment="开仓使用资金"/>
