=== lishengze/Docs-Notes/future_doc/NetMonitor_vss/datamodel/commonEnv/XTP.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT XTP (packages,fields,entities)>
<!ATTLIST XTP
	author CDATA #REQUIRED
	version CDATA #REQUIRED
	head (XTP) #REQUIRED
	comment CDATA #REQUIRED
>
<!ELEMENT packages (package*)>
<!ELEMENT package (field*)>
<!ATTLIST package
	name CDATA #REQUIRED
	tid CDATA #REQUIRED
	comment CDATA #REQUIRED
	usage (exchangeInit|sgInit|dbmt|request|response|notifyOut|notifyIn|tinit) #REQUIRED
>
<!ELEMENT field EMPTY>
<!ATTLIST field
	name CDATA #REQUIRED
	minOccur CDATA #REQUIRED
	maxOccur CDATA #REQUIRED
>
<!ELEMENT fields (fieldDefine*)>
<!ELEMENT fieldDefine (item*)>
<!ATTLIST fieldDefine
	ref CDATA #IMPLIED
	name CDATA #REQUIRED
	fid CDATA #REQUIRED
	comment CDATA #REQUIRED
>
<!ELEMENT item EMPTY>
<!ATTLIST item
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT Entity ((Field | Ref)*)>
<!ATTLIST Entity
	name CDATA #REQUIRED
	title CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT entities (Entity*)>
<!ELEMENT Field EMPTY>
<!ATTLIST Field
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	label CDATA #REQUIRED
	description CDATA #IMPLIED
	notnull (no | yes) #IMPLIED
	iskey (no | yes) #IMPLIED
>
<!ELEMENT Ref EMPTY>
<!ATTLIST Ref
	entity CDATA #REQUIRED
	iskey (yes|no) #IMPLIED
>

=== lishengze/Docs-Notes/future_doc/NetMonitor_vss/datamodel/env/XTPMisc.xml
<?xml version="1.0" encoding="GB2312"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by wangzhaodong (ORiON) -->
<!DOCTYPE XTP SYSTEM "../commonEnv/XTP.dtd">
<XTP author="赵鸿昊" version="1.0" head="XTP" comment="XTP协议中用到的各种包和域">
	<packages>
		<package name="Nop" tid="0x00000009" comment="空操作" usage="request">
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspError" tid="0x00000001" comment="错误应答" usage="response">
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqUserLogin" tid="0x00001001" comment="用户登录请求" usage="request">
			<field name="UserLogin" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspUserLogin" tid="0x00001002" comment="用户登录应答" usage="response">
			<field name="UserLogin" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqUserLogout" tid="0x00001003" comment="用户退出请求" usage="request">
			<field name="UserLogout" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspUserLogout" tid="0x00001004" comment="用户退出应答" usage="response">
			<field name="UserLogout" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqOrderInsert" tid="0x00001005" comment="报单录入请求" usage="request">
			<field name="InputOrder" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspOrderInsert" tid="0x00001006" comment="报单录入应答" usage="response">
			<field name="InputOrder" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqOrderAction" tid="0x00001007" comment="报单操作请求" usage="request">
			<field name="OrderAction" minOccur="1" maxOccur="*"/>
		</package>
		<package name="RspOrderAction" tid="0x00001008" comment="报单操作应答" usage="response">
			<field name="OrderAction" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqQuoteInsert" tid="0x00001009" comment="报价录入请求" usage="request">
			<field name="InputQuote" minOccur="1" maxOccur="*"/>
		</package>
		<package name="RspQuoteInsert" tid="0x0000100A" comment="报价录入应答" usage="response">
			<field name="InputQuote" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqQuoteAction" tid="0x0000100B" comment="报价操作请求" usage="request">
			<field name="QuoteAction" minOccur="1" maxOccur="*"/>
		</package>
		<package name="RspQuoteAction" tid="0x0000100C" comment="报价操作应答" usage="response">
			<field name="QuoteAction" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqOTCOrderInsert" tid="0x0000100D" comment="OTC报单录入请求" usage="request">
			<field name="OTCOrder" minOccur="1" maxOccur="*"/>
		</package>
		<package name="RspOTCOrderInsert" tid="0x0000100E" comment="OTC报单录入应答" usage="response">
			<field name="OTCOrder" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqUserPasswordUpdate" tid="0x0000100F" comment="用户密码修改请求" usage="request">
			<field name="UserPasswordUpdate" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspUserPasswordUpdate" tid="0x00001010" comment="用户密码修改应答" usage="response">
			<field name="UserPasswordUpdate" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqExecOrderInsert" tid="0x00001011" comment="执行宣告录入请求" usage="request">
			<field name="InputExecOrder" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspExecOrderInsert" tid="0x00001012" comment="执行宣告录入应答" usage="response">
			<field name="InputExecOrder" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqExecOrderAction" tid="0x00001013" comment="执行宣告操作请求" usage="request">
			<field name="ExecOrderAction" minOccur="1" maxOccur="*"/>
		</package>
		<package name="RspExecOrderAction" tid="0x00001014" comment="执行宣告操作应答" usage="response">
			<field name="ExecOrderAction" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqAdminOrderInsert" tid="0x00001015" comment="管理报单录入请求" usage="request">
			<field name="InputAdminOrder" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspAdminOrderInsert" tid="0x00001016" comment="管理报单录入应答" usage="response">
			<field name="InputAdminOrder" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqCombOrderInsert" tid="0x00001017" comment="组合报单录入请求" usage="request">
			<field name="InputCombOrder" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspCombOrderInsert" tid="0x00001018" comment="组合报单录入应答" usage="response">
			<field name="InputCombOrder" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqBulletin" tid="0x00002005" comment="交易所公告请求" usage="request">
			<field name="Bulletin" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspBulletin" tid="0x00002006" comment="交易所公告请求应答" usage="response">
			<field name="Bulletin" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqInstrumentStatusUpdate" tid="0x00002007" comment="合约交易状态改变请求" usage="request">
			<field name="InstrumentStatus" minOccur="1" maxOccur="*"/>
		</package>
		<package name="RspInstrumentStatusUpdate" tid="0x00002008" comment="合约交易状态改变应答" usage="response">
			<field name="InstrumentStatus" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqForceUserExit" tid="0x0000200B" comment="强制用户退出请求" usage="request">
			<field name="ForceUserExit" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspForceUserExit" tid="0x0000200C" comment="强制用户退出应答" usage="response">
			<field name="ForceUserExit" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqForceUserLogout" tid="0x0000200D" comment="用户会话删除请求" usage="request">
			<field name="ForceUserExit" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspForceUserLogout" tid="0x0000200E" comment="用户会话删除应答" usage="response">
			<field name="ForceUserExit" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqExchangeDataSyncStatusUpdate" tid="0x00002013" comment="交易所数据同步状态改变请求" usage="request">
			<field name="ExchangeDataSyncStatus" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspExchangeDataSyncStatusUpdate" tid="0x00002014" comment="交易所数据同步状态改变应答" usage="response">
			<field name="ExchangeDataSyncStatus" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqSGDataSyncStatusUpdate" tid="0x00002015" comment="结算组数据同步状态改变请求" usage="request">
			<field name="SGDataSyncStatus" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspSGDataSyncStatusUpdate" tid="0x00002016" comment="结算组数据同步状态改变应答" usage="response">
			<field name="SGDataSyncStatus" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqExchangeDataSync" tid="0x00002801" comment="交易所数据同步请求" usage="request">
			<field name="ExchangeTradingDay" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspExchangeDataSync" tid="0x00002802" comment="交易所数据同步应答" usage="response">
			<field name="ExchangeTradingDay" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqSgDataSync" tid="0x00002803" comment="结算组数据同步请求" usage="request">
			<field name="SettlementSession" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspSgDataSync" tid="0x00002804" comment="结算组数据同步应答" usage="response">
			<field name="SettlementSession" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqInformation" tid="0x00002805" comment="交易所信息请求" usage="request">
			<field name="Information" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspInformation" tid="0x00002806" comment="交易所公告信息应答" usage="response">
			<field name="Information" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqFrontStatus" tid="0x00009001" comment="前置状态报告请求" usage="request">
			<field name="FrontStatus" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspFrontStatus" tid="0x00009002" comment="前置状态报告应答" usage="response">
			<field name="FrontStatus" minOccur="1" maxOccur="1"/>
			<field name="RspInfo" minOccur="1" maxOccur="1"/>
		</package>
		<package name="ReqQryPartAccount" tid="0x00004001" comment="会员资金查询请求" usage="request">
			<field name="QryPartAccount" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspQryPartAccount" tid="0x00004002" comment="会员资金查询应答" usage="response">
			<field name="RspPartAccount" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqQryOrder" tid="0x00004003" comment="报单查询请求" usage="request">
			<field name="QryOrder" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspQryOrder" tid="0x00004004" comment="报单查询应答" usage="response">
			<field name="Order" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqQryQuote" tid="0x00004005" comment="报价查询请求" usage="request">
			<field name="QryQuote" minOccur="1" maxOccur="1"/>
		</package>
		<package name="RspQryQuote" tid="0x00004006" comment="报价查询应答" usage="response">
			<field name="Quote" minOccur="1" maxOccur="*"/>
			<field name="RspInfo" minOccur="1" maxOccur="*"/>
		</package>
		<package name="ReqQryTrade" tid="0x00004007" comment="成交单查询请求" usage="request">
